#pragma once

namespace app::web_ui {

inline constexpr char kIndexHtml[] = R"HTML(<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Jenix School Bell</title>
<style>
:root{font-family:system-ui,sans-serif;color:#172033;background:#f2f5f9}*{box-sizing:border-box}body{margin:0}header{background:#123b70;color:#fff;padding:18px 5vw;display:flex;justify-content:space-between;align-items:center}header h1{font-size:1.25rem;margin:0}.wrap{max-width:1100px;margin:auto;padding:18px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(290px,1fr));gap:16px}.card{background:#fff;border-radius:12px;padding:18px;box-shadow:0 2px 12px #15294b18;margin-bottom:16px}h2{font-size:1.05rem;margin:0 0 14px}label{display:block;font-size:.85rem;margin:8px 0 4px}input,select,button,textarea{font:inherit;border:1px solid #b8c2cf;border-radius:7px;padding:9px;width:100%}textarea{font-family:ui-monospace,monospace;min-height:150px}button{background:#1769aa;color:#fff;border:0;cursor:pointer;margin-top:10px}.danger{background:#b42318}.secondary{background:#536273}.row{display:flex;gap:10px}.row>*{flex:1}.status{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.pill{padding:8px;border-radius:7px;background:#eef2f6}.device-clock{background:#e8f2ff;border:1px solid #8ab8e8;border-radius:10px;padding:14px;margin-bottom:12px}.device-clock strong{display:block;font-size:1.65rem;font-variant-numeric:tabular-nums;margin:4px 0}.ok{color:#067647}.bad{color:#b42318}table{width:100%;border-collapse:collapse;min-width:820px}th,td{padding:7px;border-bottom:1px solid #e3e8ef;text-align:left}td input,td select{min-width:90px}.scroll{overflow:auto}.days{white-space:nowrap}.days label{display:inline}.days input{width:auto}pre{max-height:260px;overflow:auto;background:#111827;color:#e5e7eb;padding:12px;border-radius:8px;white-space:pre-wrap}#msg{position:fixed;right:16px;bottom:16px;max-width:380px;background:#172033;color:white;padding:12px 16px;border-radius:8px;display:none}small{color:#667085}a{color:#d8ebff}</style>
</head>
<body>
<header><h1>Jenix School Bell Control Panel</h1><span><a href="/api/v1/capabilities" target="_blank">API v1</a></span></header>
<main class="wrap">
<div class="grid">
 <section class="card"><h2>Device status</h2><div class="device-clock"><span>ESP32 / DS3231 schedule time</span><strong id="deviceClock">--</strong><small id="deviceClockMeta">Waiting for device clock</small></div><div id="status" class="status"></div><button class="secondary" onclick="loadAll()">Refresh</button></section>
 <section class="card"><h2>Manual bell</h2><label>Sound</label><select id="testSound" onchange="manualSoundId=this.value;stopPreview()"></select><div class="row"><div><label>Duration (seconds)</label><input id="testDuration" type="number" min="1" max="3600" value="5"></div></div><button onclick="testBell()">Play on bell output</button><button onclick="previewSound()">Preview on this phone</button><audio id="soundPreview" controls preload="none"></audio><button onclick="diagnosticTone()">Play 1 kHz hardware test tone</button><small>The phone preview streams the selected internal-flash or SD file. The test tone bypasses file decoding to verify the PCM5102 and amplifier path.</small></section>
 <section class="card"><h2>Physical push to talk</h2><div id="announcementLiveState" class="pill">Checking microphone status...</div><p><small>Hold the GPIO15 switch to GND to announce. Microphone audio input is GPIO7. If a scheduled bell becomes due, the announcement pauses, the bell plays, then the announcement resumes while PTT remains held.</small></p><label><input id="pttEnabled" type="checkbox" style="width:auto"> Enable physical PTT</label><label>Microphone digital gain (%)</label><input id="pttGain" type="number" min="25" max="800" value="200"><button onclick="saveAnnouncementConfig()">Save announcement settings</button></section>
</div>
<div class="grid">
 <section class="card"><h2>School and Wi-Fi</h2><label>School name</label><input id="schoolName"><label>School Wi-Fi SSID</label><input id="wifiSsid"><label>Wi-Fi password</label><input id="wifiPassword" type="password" placeholder="Leave blank to keep current password"><label>Volume (%)</label><input id="volume" type="number" min="0" max="100"><button onclick="saveConfig()">Save and connect</button><small>The setup AP remains available during commissioning.</small></section>
 <section class="card"><h2>Date, time and timezone</h2><p><small>Every schedule is matched against the ESP32/DS3231 time shown above, not the phone clock.</small></p><label>Timezone name</label><input id="timezone" placeholder="Asia/Kolkata"><label>POSIX timezone rule</label><input id="timezonePosix" placeholder="IST-5:30"><button onclick="saveTimezone()">Apply timezone</button><label>School local date/time</label><input id="localTime" type="datetime-local"><button onclick="setBrowserTime()">Use this browser's current time</button><button onclick="saveTime()">Save to DS3231 RTC</button></section>
</div>
<section class="card"><h2>Jenix One cloud bridge</h2><label><input id="cloudEnabled" type="checkbox" style="width:auto"> Enable MQTT connection</label><div class="row"><div><label>HOME ID</label><input id="cloudHomeId" placeholder="home-..."></div><div><label>MQTT host</label><input id="mqttHost" value="mqtt.iotsoft.in"></div><div><label>MQTT port</label><input id="mqttPort" type="number" min="1" max="65535" value="1883"></div></div><div class="row"><div><label>Device MQTT username</label><input id="mqttUsername"></div><div><label>Device MQTT password</label><input id="mqttPassword" type="password" placeholder="Leave blank to keep current password"></div></div><button onclick="saveCloud()">Save cloud connection</button><small id="cloudState">Cloud is optional; the bell and schedules remain fully local.</small></section>
<section class="card"><h2>Internal-flash sound library</h2><input id="audioFiles" type="file" accept=".mp3,.wav,audio/mpeg,audio/wav" multiple><button onclick="uploadSounds()">Upload selected sounds</button><div class="row"><select id="deleteSoundSelect"></select><button class="danger" onclick="deleteSound()">Delete selected sound</button></div><div id="uploadProgress"></div><small>MP3 or WAV. Available space is reported under Device status; a sound used by a schedule cannot be deleted.</small></section>
<section class="card"><h2>Temporary festival slot</h2><input id="festivalFile" type="file" accept=".mp3,.wav,audio/mpeg,audio/wav"><button onclick="uploadFestival()">Upload / replace festival track</button><button class="danger" onclick="clearFestival()">Clear festival slot</button><div id="festivalState" class="pill">Checking festival slot...</div><small>Use sound ID <code>festival/current</code> for manual ringing or one schedule entry. Remove that schedule reference before clearing the slot.</small></section>
<section class="card"><h2>SD card /bells browser</h2><div class="row"><button class="secondary" onclick="browseBellParent()">Up one folder</button><button class="secondary" onclick="browseBells(bellBrowserPath,0)">Refresh</button></div><p><small id="bellBrowserLocation">/bells</small></p><div id="bellBrowserEntries"></div><div class="row"><button id="bellBrowserPrev" class="secondary" onclick="browseBells(bellBrowserPath,Math.max(0,bellBrowserOffset-50))">Previous</button><button id="bellBrowserNext" class="secondary" onclick="browseBells(bellBrowserPath,bellBrowserOffset+50)">Next</button></div><small>Only MP3/WAV files inside /bells are exposed. Select a file for manual playback, preview it on this phone, or add a new schedule row using it.</small></section>
 <section class="card"><h2>Timetable mode</h2><label><input id="automationEnabled" type="checkbox" style="width:auto"> Automatic scheduled bells enabled</label><button class="secondary" onclick="saveAutomation()">Save pause/resume state</button><label>Default active profile</label><select id="profileSelect"></select><button onclick="activateProfile()">Activate selected profile</button><small>Manual bell remains available while automatic bells are paused. Date rules can temporarily select Summer, Winter or Exam profiles without changing this default.</small><details><summary>Advanced profile and calendar-rule JSON</summary><textarea id="profileJson"></textarea><button onclick="saveProfilePack()">Validate and save complete profile pack</button></details></section>
<section class="card"><h2>Bell schedule for active profile</h2><button style="max-width:180px" onclick="addSchedule()">Add bell</button><div class="scroll"><table><thead><tr><th>Name</th><th>Time</th><th>Sound</th><th>Seconds</th><th>Days</th><th>Enabled</th><th></th></tr></thead><tbody id="scheduleRows"></tbody></table></div><button onclick="saveSchedules()">Save active-profile schedule</button></section>
<div class="grid">
 <section class="card"><h2>Holidays / closed dates</h2><textarea id="holidayJson" placeholder='[{"date":"2026-10-02","name":"Holiday","type":"holiday"}]'></textarea><button onclick="saveHolidays()">Validate and save holidays</button></section>
 <section class="card"><h2>Manual bell presets</h2><textarea id="presetJson" placeholder='[{"id":1,"label":"Assembly","sound_id":"default","duration":10,"category":"assembly"}]'></textarea><button onclick="savePresets()">Validate and save presets</button></section>
</div>
<section class="card"><h2>Runtime activity log</h2><div class="row"><button class="secondary" onclick="loadLogs()">Refresh logs</button><button class="danger" onclick="clearLogs()">Clear logs</button></div><pre id="logOutput">No logs</pre></section>
<section class="card"><h2>SD card maintenance</h2><p>This permanently deletes everything on the inserted card and creates a FAT32 filesystem.</p><button class="danger" onclick="formatSd()">Format SD card as FAT32</button></section>
</main><div id="msg"></div>
<script>
const A='/api/v1';let sounds=[],bellBrowserSounds=new Map(),manualSoundId='',profilePack={active_profile_id:'regular',profiles:[],calendar_rules:[]},deviceClockBase=null,deviceClockSync=0,deviceTimezone='',bellBrowserPath='/bells',bellBrowserParent=null,bellBrowserOffset=0;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function note(t,bad=false){let e=document.querySelector('#msg');e.textContent=t;e.style.background=bad?'#b42318':'#172033';e.style.display='block';setTimeout(()=>e.style.display='none',4500)}
async function api(path,opt={}){let r=await fetch(A+path,opt);let text=await r.text();let data;try{data=JSON.parse(text)}catch{data={message:text}}if(!r.ok)throw Error(data.error||data.message||('HTTP '+r.status));return data}
function parseDeviceClock(v){let m=String(v||'').match(/^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2}):(\d{2})$/);return m?Date.UTC(+m[1],+m[2]-1,+m[3],+m[4],+m[5],+m[6]):null}
function tickDeviceClock(){if(deviceClockBase===null){deviceClock.textContent='RTC unavailable';deviceClockMeta.textContent='Set and save the DS3231 clock';return}let d=new Date(deviceClockBase+Date.now()-deviceClockSync),p=n=>String(n).padStart(2,'0'),days=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];deviceClock.textContent=`${d.getUTCFullYear()}-${p(d.getUTCMonth()+1)}-${p(d.getUTCDate())}  ${p(d.getUTCHours())}:${p(d.getUTCMinutes())}:${p(d.getUTCSeconds())}`;deviceClockMeta.textContent=`${days[d.getUTCDay()]} • ${deviceTimezone||'school local timezone'} • schedule execution reference`}
async function loadStatus(){let s=await api('/status'),free=s.internal_storage?.free_bytes;deviceClockBase=parseDeviceClock(s.local_time);deviceClockSync=Date.now();deviceTimezone=s.timezone||'';tickDeviceClock();automationEnabled.checked=s.automation_enabled!==false;document.querySelector('#status').innerHTML=[['State',s.state],['Audio',s.audio?.busy?s.audio.busy_reason:'Idle'],['Device ID',s.device_id],['Auto bells',s.automation_enabled?'Running':'Paused'],['Internal flash',s.internal_storage_ready?(Number.isFinite(free)?(free/1048576).toFixed(2)+' MiB free':'Ready'):'Not ready'],['SD card',s.sd_ready?'Ready':'Not inserted'],['RTC',s.time_valid?'Valid':'Needs setting'],['Setup AP',s.ap_ssid],['School Wi-Fi',s.station_connected?'Connected':'Not connected'],['LAN IP',s.station_ip||'-'],['mDNS',s.mdns_hostname?s.mdns_hostname+'.local':'-'],['Jenix cloud',s.cloud?.connected?'Connected':(s.cloud?.configured?'Offline':'Not configured')],['Default plan',s.active_profile_id||'-'],['Today plan',s.resolved_profile_id||'-'],['Holiday today',s.holiday_today?'Yes':'No'],['API',s.api_version]].map(x=>`<div class="pill"><b>${esc(x[0])}</b><br><span>${esc(x[1])}</span></div>`).join('')}
async function loadConfig(){let c=await api('/config');schoolName.value=c.school_name||'';wifiSsid.value=c.wifi?.ssid||'';volume.value=c.volume_percent??80;timezone.value=c.timezone||'';timezonePosix.value=c.timezone_posix||'';pttEnabled.checked=c.announcement?.physical_ptt_enabled!==false;pttGain.value=c.announcement?.mic_gain_percent??200}
async function loadAnnouncementStatus(){let a=await api('/announcement/status'),active=a.announcement_active,ring=a.bell_active;announcementLiveState.className='pill '+(active?'ok':'');announcementLiveState.innerHTML=`<b>${ring?'BELL PLAYING':(active?'ANNOUNCEMENT LIVE':'IDLE')}</b><br><small>Busy: ${esc(a.busy_reason)} | PTT GPIO${esc(a.physical_ptt_gpio)} | MIC GPIO${esc(a.mic_adc_gpio)} | gain ${esc(a.mic_gain_percent)}%</small>`}
async function loadCloud(){let c=await api('/cloud');cloudEnabled.checked=c.enabled===true;cloudHomeId.value=c.homeId||'';mqttHost.value=c.mqttHost||'mqtt.iotsoft.in';mqttPort.value=c.mqttPort||1883;mqttUsername.placeholder=c.mqttUsernameConfigured?'Configured - leave blank to keep':'Required';cloudState.textContent=c.connected?'Connected to Jenix One':(c.configured?'Configured; waiting for connection':'HOME ID and MQTT username are required')}
async function loadSounds(){let d=await api('/sounds'),selected=manualSoundId||testSound.value;sounds=d.sounds||[];let label=s=>s.name+(Number.isFinite(s.duration)?` (${s.duration.toFixed(1)}s)`:'');let h=sounds.map(s=>`<option value="${esc(s.id)}">${esc(label(s))}</option>`).join('');testSound.innerHTML=h;if(selected&&sounds.some(s=>s.id===selected))testSound.value=selected;manualSoundId=testSound.value;let deletable=sounds.filter(s=>s.source==='internal-flash');deleteSoundSelect.innerHTML=deletable.map(s=>`<option value="${esc(s.name)}">${esc(label(s))}</option>`).join('');document.querySelectorAll('.sound').forEach(sel=>{let v=sel.value||sel.dataset.value;sel.innerHTML=h;sel.value=v})}
async function browseBells(path='/bells',offset=0){let d=await api('/sd/browse?path='+encodeURIComponent(path)+'&offset='+offset+'&limit=50');bellBrowserPath=d.path;bellBrowserParent=d.parent;bellBrowserOffset=d.offset||0;bellBrowserLocation.textContent=d.path+` (${d.total||0} items)`;bellBrowserPrev.disabled=bellBrowserOffset<=0;bellBrowserNext.disabled=!d.has_more;(d.entries||[]).filter(e=>e.type!=='folder'&&e.sound_id).forEach(e=>bellBrowserSounds.set(e.sound_id,{id:e.sound_id,name:e.path?.replace(/^\/bells\//,'')||e.name,format:e.format,duration:e.duration,content_url:e.content_url}));bellBrowserEntries.innerHTML=(d.entries||[]).map(e=>{let p=encodeURIComponent(e.path).replace(/'/g,'%27'),id=encodeURIComponent(e.sound_id||'').replace(/'/g,'%27'),meta=e.type==='folder'?'Folder':`${e.format?.toUpperCase()||'Audio'} - ${Number.isFinite(e.duration)?e.duration.toFixed(1)+' sec':'duration unknown'}`;return `<div class="pill" style="margin:7px 0"><b>${e.type==='folder'?'[DIR]':'[AUDIO]'} ${esc(e.name)}</b><br><small>${esc(meta)}</small>${e.type==='folder'?`<button onclick="openBellFolder('${p}')">Open</button>`:`<div class="row"><button onclick="chooseBellSound('${id}','select')">Select</button><button onclick="chooseBellSound('${id}','preview')">Preview</button><button onclick="chooseBellSound('${id}','schedule')">Add schedule</button></div>`}</div>`}).join('')||'<div class="pill">No MP3/WAV files in this folder</div>'}
function openBellFolder(path){browseBells(decodeURIComponent(path),0).catch(e=>note(e.message,true))}
function browseBellParent(){if(bellBrowserParent)browseBells(bellBrowserParent,0).catch(e=>note(e.message,true))}
function chooseBellSound(encodedId,action){let id=decodeURIComponent(encodedId),sound=sounds.find(s=>s.id===id)||bellBrowserSounds.get(id);if(!sound&&id.startsWith('bells/'))sound={id,name:id.slice(6),duration:null,content_url:A+'/sounds/content?path='+encodeURIComponent('/'+id)};if(!sound)return note('This SD entry is no longer available',true);if(!sounds.some(s=>s.id===id)){sounds.push(sound);let option=new Option(sound.name+(Number.isFinite(sound.duration)?` (${sound.duration.toFixed(1)}s)`:''),id);testSound.add(option);document.querySelectorAll('.sound').forEach(sel=>sel.add(option.cloneNode(true)))}testSound.value=id;manualSoundId=id;if(action==='preview')return previewSound();if(action==='schedule'){addSchedule({name:'Scheduled Bell',sound_id:id,duration:Math.max(1,Math.ceil(sound.duration||5))});document.querySelector('#scheduleRows').lastElementChild?.scrollIntoView({behavior:'smooth',block:'center'});note('Sound added to a new schedule row');return}note('Sound selected for bell playback')}
async function loadProfiles(){profilePack=await api('/schedule-profiles');profileJson.value=JSON.stringify(profilePack,null,2);profileSelect.innerHTML=(profilePack.profiles||[]).filter(p=>p.enabled!==false).map(p=>`<option value="${esc(p.id)}">${esc(p.name)} (${esc(p.category)})</option>`).join('');profileSelect.value=profilePack.active_profile_id}
async function loadSchedules(){let d=await api('/schedules');scheduleRows.innerHTML='';(d.schedules||[]).forEach(addSchedule)}
function soundOptions(v){return sounds.map(s=>`<option value="${esc(s.id)}" ${s.id===v?'selected':''}>${esc(s.name)}</option>`).join('')}
function addSchedule(x={}){let days=x.days||[1,2,3,4,5],tr=document.createElement('tr');tr.innerHTML=`<td><input class="name" value="${esc(x.name||'Period Bell')}"></td><td><input class="time" type="time" value="${esc(x.time||'08:00')}"></td><td><select class="sound">${soundOptions(x.sound_id||sounds[0]?.id||'default')}</select></td><td><input class="duration" type="number" min="1" max="3600" value="${x.duration||5}"></td><td class="days">${['Su','Mo','Tu','We','Th','Fr','Sa'].map((n,i)=>`<label><input type="checkbox" data-day="${i}" ${days.includes(i)?'checked':''}>${n}</label>`).join('')}</td><td><input class="enabled" type="checkbox" ${x.enabled!==false?'checked':''}></td><td><button class="danger" onclick="this.closest('tr').remove()">Delete</button></td>`;scheduleRows.appendChild(tr)}
async function saveSchedules(){let arr=[...scheduleRows.rows].map((r,i)=>({id:i+1,name:r.querySelector('.name').value.trim(),time:r.querySelector('.time').value,type:'period',sound_id:r.querySelector('.sound').value,duration:Number(r.querySelector('.duration').value),days:[...r.querySelectorAll('[data-day]:checked')].map(e=>Number(e.dataset.day)),enabled:r.querySelector('.enabled').checked}));await api('/schedules',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(arr)});note('Schedule saved')}
async function activateProfile(){await api('/active-profile',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({profile_id:profileSelect.value})});await loadAll();note('Default timetable activated')}
async function saveAutomation(){let enabled=automationEnabled.checked;await api('/automation',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({enabled})});await loadStatus();note(enabled?'Automatic bells resumed':'Automatic bells paused')}
async function saveProfilePack(){let value;try{value=JSON.parse(profileJson.value)}catch{return note('Profile JSON is invalid',true)}await api('/schedule-profiles',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(value)});await loadAll();note('Profiles and date rules saved')}
async function loadHolidays(){let d=await api('/holidays');holidayJson.value=JSON.stringify(d.holidays||[],null,2)}
async function saveHolidays(){let value;try{value=JSON.parse(holidayJson.value)}catch{return note('Holiday JSON is invalid',true)}await api('/holidays',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(value)});await loadStatus();note('Holidays saved')}
async function loadPresets(){let d=await api('/presets');presetJson.value=JSON.stringify(d.presets||[],null,2)}
async function savePresets(){let value;try{value=JSON.parse(presetJson.value)}catch{return note('Preset JSON is invalid',true)}await api('/presets',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(value)});note('Bell presets saved')}
async function loadLogs(){let d=await api('/logs?limit=200');logOutput.textContent=(d.logs||[]).join('\n')||'No logs'}
async function clearLogs(){if(!confirm('Clear activity logs?'))return;await api('/logs',{method:'DELETE'});await loadLogs();note('Logs cleared')}
async function saveConfig(){let body={school_name:schoolName.value.trim(),volume_percent:Number(volume.value),wifi:{ssid:wifiSsid.value.trim()}};if(wifiPassword.value)body.wifi.password=wifiPassword.value;await api('/config',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});wifiPassword.value='';note('Configuration saved; connecting to school Wi-Fi')}
async function saveAnnouncementConfig(){await api('/config',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({announcement:{physical_ptt_enabled:pttEnabled.checked,mic_gain_percent:Number(pttGain.value)}})});await loadAnnouncementStatus();note('Announcement settings saved')}
async function saveTimezone(){await api('/config',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({timezone:timezone.value.trim(),timezone_posix:timezonePosix.value.trim()})});await loadStatus();note('Timezone applied and saved')}
async function saveCloud(){await api('/cloud',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({enabled:cloudEnabled.checked,homeId:cloudHomeId.value.trim(),mqttHost:mqttHost.value.trim(),mqttPort:Number(mqttPort.value)})});let credential={activateForCloudBroker:cloudEnabled.checked};if(mqttUsername.value.trim())credential.mqttUsername=mqttUsername.value.trim();if(mqttPassword.value)credential.mqttPassword=mqttPassword.value;await api('/device-mqtt-credential',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(credential)});mqttUsername.value='';mqttPassword.value='';await loadCloud();note('Jenix One cloud settings saved')}
function setBrowserTime(){let d=new Date(Date.now()-new Date().getTimezoneOffset()*60000);localTime.value=d.toISOString().slice(0,16)}
async function saveTime(){if(!localTime.value)return note('Select date and time',true);await api('/time',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({local_time:localTime.value})});note('RTC updated');loadStatus()}
async function testBell(){let soundId=manualSoundId||testSound.value;if(!soundId)return note('Choose a sound first',true);await api('/bell/ring',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:'WebUI test',soundId,duration:Number(testDuration.value)})});note('Bell played')}
function stopPreview(){soundPreview.pause();soundPreview.removeAttribute('src');soundPreview.load()}
async function previewSound(){let selected=sounds.find(s=>s.id===testSound.value);if(!selected)return note('Choose a sound first',true);soundPreview.src=selected.content_url||('/api/v1/sounds/content?name='+encodeURIComponent(selected.name));try{await soundPreview.play();note('Preview playing on this phone')}catch(e){note('Phone preview failed: '+e.message,true)}}
async function diagnosticTone(){await api('/audio/diagnostic',{method:'POST'});note('Diagnostic tone played')}
async function uploadSounds(){let fs=[...audioFiles.files];if(!fs.length)return note('Choose MP3/WAV files first',true);for(let i=0;i<fs.length;i++){let f=fs[i];uploadProgress.textContent=`Uploading ${i+1}/${fs.length}: ${f.name}`;await api('/internal/sounds?name='+encodeURIComponent(f.name),{method:'POST',headers:{'Content-Type':'application/octet-stream'},body:f})}uploadProgress.textContent='Upload complete';audioFiles.value='';await loadSounds();note('Sounds uploaded to internal flash')}
async function deleteSound(){let name=deleteSoundSelect.value;if(!name||!confirm('Delete '+name+'?'))return;await api('/sounds?name='+encodeURIComponent(name),{method:'DELETE'});await loadSounds();note('Sound deleted')}
async function loadFestival(){let d=await api('/festival'),f=d.file;festivalState.innerHTML=f?`<b>READY: ${esc(f.name)}</b><br><small>${esc(f.format?.toUpperCase())} - ${Number.isFinite(f.duration)?f.duration.toFixed(1)+' sec':'duration unknown'} - ${esc(f.bytes)} bytes</small>`:'Festival slot is empty'}
async function uploadFestival(){let f=festivalFile.files[0];if(!f)return note('Choose one MP3/WAV festival track',true);await api('/festival/upload?name='+encodeURIComponent(f.name),{method:'POST',headers:{'Content-Type':'application/octet-stream'},body:f});festivalFile.value='';await Promise.all([loadFestival(),loadSounds()]);note('Festival track is ready')}
async function clearFestival(){if(!confirm('Clear the temporary festival track?'))return;await api('/festival',{method:'DELETE'});await Promise.all([loadFestival(),loadSounds()]);note('Festival slot cleared')}
async function formatSd(){if(prompt('This deletes the entire SD card. Type FORMAT to continue:')!=='FORMAT')return;await api('/sd/format',{method:'POST',headers:{'Content-Type':'application/json'},body:'{"confirm":"FORMAT"}'});note('SD formatted as FAT32');await loadAll()}
async function loadAll(){try{await Promise.all([loadStatus(),loadConfig(),loadCloud(),loadAnnouncementStatus(),loadFestival()]);await loadSounds();await browseBells('/bells',0).catch(e=>{bellBrowserEntries.innerHTML='<div class="pill">Optional SD /bells library is unavailable: '+esc(e.message)+'</div>'});await loadProfiles();await loadSchedules();await Promise.all([loadHolidays(),loadPresets(),loadLogs()]);if(!localTime.value)setBrowserTime()}catch(e){note(e.message,true)}}
loadAll();
setInterval(tickDeviceClock,1000);setInterval(()=>loadAnnouncementStatus().catch(()=>{}),1000);setInterval(()=>loadStatus().catch(()=>{}),30000);
</script></body></html>)HTML";

}  // namespace app::web_ui
