[platformio]
default_envs = esp32-c3-supermini

[env]
test_framework = unity
build_flags =
  -Isrc

[env:esp32-c3-supermini]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
board_build.f_cpu = 80000000L
monitor_speed = 115200
upload_speed = 460800
board_build.partitions = partitions.csv
build_unflags =
  -std=gnu++11
build_flags =
  ${env.build_flags}
  -std=gnu++17
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D ARDUINO_USB_MODE=1
  -D LOG_LOCAL_LEVEL=ESP_LOG_INFO
lib_deps =
  bblanchon/ArduinoJson@^6.21.5
  h2zero/NimBLE-Arduino@^1.4.2
  knolleary/PubSubClient@^2.8

[env:native]
platform = native
test_build_src = no
build_flags =
  ${env.build_flags}
  -std=gnu++17
